### ISSUE TITLE
OnShoot Error

### ISSUE THREAD

**Issue by nonatus** [TruthfullyHonest/ScpMessages#2]
Method "OnShoot" of the class "ScpMessages.EventHandlers" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler`1[[Exiled.Events.EventArgs.ShotEventArgs, Exiled.Events, Version=2.11.1.0, Culture=neutral, PublicKeyToken=null]]"
[2021-07-26 19:23:43.253 +03:00] [ERROR] [Exiled.Events] System.NullReferenceException: Object reference not set to an instance of an object
  at ScpMessages.TokenReplacer.ReplaceAfterToken (System.String source, System.Char token, ScpMessages.TwoTupleSOList valuePairs) [0x0000e] in <c25ddd198caf4c3e8ab1a7c4d2660c45>:0
  at ScpMessages.EventHandlers.ProcessShotHit (Exiled.Events.EventArgs.ShotEventArgs Shot) [0x00352] in <c25ddd198caf4c3e8ab1a7c4d2660c45>:0
  at ScpMessages.EventHandlers.OnShoot (Exiled.Events.EventArgs.ShotEventArgs Shoot) [0x00025] in <c25ddd198caf4c3e8ab1a7c4d2660c45>:0
  at Exiled.Events.Extensions.Event.InvokeSafely[T] (Exiled.Events.Events+CustomEventHandler`1[TEventArgs] ev, T arg) [0x00024] in <eb85128a82174c588a2176a34c5ed92b>:0

After updates it's still here

**Comment by HonestResolv3** [comment]
Odd, I thought I fixed it, even doing extensive testing with Human shooting SCP, Human shooting Human. I will look into this

**Comment by HonestResolv3** [comment]
What causes this error to occur? @nonatus

Are you shooting a Human as a Human? Also tell me the configuration you have for any human related messages

**Comment by nonatus** [comment]
Shooting Human to Human.

Configs are here:
**scp_messages:**
  is_enabled: true
  enable_debug_startup_message: false
  enable_toggle_message_on_join: false
  force_messages_enabled_on_join: true
  damage_message_enabled: true
  door_message_enabled: true
  medical_item_message_enabled: true
  humans_receive_message: true
  scps_receive_message: true
  damage_message_chance: 100
  door_message_chance: 100
  medical_item_message_chance: 100
  hitbox_translations:
    HEAD: голову
    ARM: руку
    BODY: тело
    LEG: ногу
  fall_damage_message: 
  bullet_damage_message: Пуля попала вам в %hitbox.
  tesla_damage_message: Вас ударило электрическим током.
  grenade_damage_message: 
  micro_hid_damage_message: Вас ударило электрическим током.
  human_gun_attack_message: 
  human_gun_attack_scp_message: 
  human_grenade_attack_message: 
  human_micro_hid_attack_message: 
  scp049_attack_message: 
  scp0492_attack_message: 
  scp096_attack_message: 
  scp106_attack_message: 
  scp173_attack_message: 
  scp93953_attack_message: 
  scp93989_attack_message: 
  scp049_attacked_message: 
  scp0492_attacked_message: 
  scp096_attacked_message: 
  scp106_attacked_message: 
  scp173_attacked_message: 
  scp93953_attacked_message: 
  scp93989_attacked_message: 
  scp049_damage_message: Вас тронул чумной доктор. Смерть наступила мгновенно.
  scp0492_damage_message: 
  scp096_damage_message: Вы были разодраны.
  scp106_damage_message: 
  scp173_damage_message: Перелом позвоночника. Смерть наступила мгновенно.
  scp939_damage_message: 
  locked_door_message: Требуется ключ-карта.
  locked_door_keycard_message: Нужна более карта с большим УД.
  full_lockdown_message: Дверь заблокирована.
  unlocked_door_keycard_message: Сканер использован.
  bypass_door_message: Сканер использован.
  bypass_door_keycard_message: Сканер использован.
  painkiller_heal_message: Вы приняли таблетки, похожие на болеутоляющие.
  medkit_heal_message: Вы использовали аптечку первой помощи
  adrenaline_heal_message: Вы использовали инъекцию.
  scp500_heal_message: Вы приняли таблетки, похожие на болеутоляющие.
  scp207_heal_message: Вы выпили бутылочку сладкой Coca-Cola.


And there is a question, can there be support for CustomDoorAccess? Because if player opens a door there is "locked_door_keycard_message" message.

**Comment by HonestResolv3** [comment]
I honestly am not sure on how to add support for other plugins so I might give it a try, main priority is fixing up this issue, I did not know such item existed either

I'm thinking if the messages are empty for variables, it gets treated as null

**Comment by nonatus** [comment]
Wrote all of the messages but Bullet Damage still doesn't work.

**Comment by nonatus** [comment]
Fixed it
